// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDpZi-v3MIYtui4MrHbdR0cxyNQ35YQTBc',
    appId: '1:1030840900378:web:8f76738efe0f4fe5dd6aa3',
    messagingSenderId: '1030840900378',
    projectId: 'device-streaming-08042fb3',
    authDomain: 'device-streaming-08042fb3.firebaseapp.com',
    storageBucket: 'device-streaming-08042fb3.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCofsjOFcF7ItdkS3ai9ShEErcH8oCNYZI',
    appId: '1:1030840900378:android:2bc0c60361e8cc13dd6aa3',
    messagingSenderId: '1030840900378',
    projectId: 'device-streaming-08042fb3',
    storageBucket: 'device-streaming-08042fb3.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBURV7q3tr-94Xnl2Jn7mAEEWeTUODvgsY',
    appId: '1:1030840900378:ios:a58db7a70387b93fdd6aa3',
    messagingSenderId: '1030840900378',
    projectId: 'device-streaming-08042fb3',
    storageBucket: 'device-streaming-08042fb3.firebasestorage.app',
    iosBundleId: 'com.example.application',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBURV7q3tr-94Xnl2Jn7mAEEWeTUODvgsY',
    appId: '1:1030840900378:ios:a58db7a70387b93fdd6aa3',
    messagingSenderId: '1030840900378',
    projectId: 'device-streaming-08042fb3',
    storageBucket: 'device-streaming-08042fb3.firebasestorage.app',
    iosBundleId: 'com.example.application',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDpZi-v3MIYtui4MrHbdR0cxyNQ35YQTBc',
    appId: '1:1030840900378:web:502c11fc6985dd41dd6aa3',
    messagingSenderId: '1030840900378',
    projectId: 'device-streaming-08042fb3',
    authDomain: 'device-streaming-08042fb3.firebaseapp.com',
    storageBucket: 'device-streaming-08042fb3.firebasestorage.app',
  );
}
