// Generated by Hive CE
// Do not modify
// Check in to version control

import 'package:hive_ce/hive_ce.dart';
import 'package:application/data/models/anime.dart';
import 'package:application/data/models/filter.dart';
import 'package:application/data/models/translated.dart';
import 'package:application/data/models/user.dart';

extension HiveRegistrar on HiveInterface {
  void registerAdapters() {
    registerAdapter(AnimeAdapter());
    registerAdapter(CategoryAdapter());
    registerAdapter(CommentAdapter());
    registerAdapter(GenreAdapter());
    registerAdapter(SerieAdapter());
    registerAdapter(TranslatedAdapter());
    registerAdapter(UserAdapter());
  }
}

extension IsolatedHiveRegistrar on IsolatedHiveInterface {
  void registerAdapters() {
    registerAdapter(AnimeAdapter());
    registerAdapter(CategoryAdapter());
    registerAdapter(CommentAdapter());
    registerAdapter(GenreAdapter());
    registerAdapter(SerieAdapter());
    registerAdapter(TranslatedAdapter());
    registerAdapter(UserAdapter());
  }
}
