// Generated by Hive CE
// Do not modify
// Check in to version control

import 'package:hive_ce/hive_ce.dart';
import 'package:application/features/animes/data/models/anime_model.dart';
import 'package:application/features/animes/data/models/download_model.dart';
import 'package:application/features/animes/data/models/episode_model.dart';
import 'package:application/features/calendar/data/models/calendar_model.dart';
import 'package:application/features/calendar/data/models/timer_model.dart';
import 'package:application/features/common/data/models/helpers/pagination.dart';
import 'package:application/features/common/data/models/helpers/translated.dart';
import 'package:application/features/common/data/models/miscs/item_model.dart';
import 'package:application/features/explore/data/models/genre_model.dart';
import 'package:application/features/player/data/model/download/completed_models.dart';
import 'package:application/features/player/data/model/parser_models.dart';
import 'package:application/features/player/data/model/service/download_models.dart';
import 'package:application/features/player/data/model/timeline_model.dart';
import 'package:application/features/profile/data/models/avatar_model.dart';
import 'package:application/features/profile/data/models/notifications/ep_notif_model.dart';
import 'package:application/features/profile/data/models/notifications/notification_model.dart';
import 'package:application/features/profile/data/models/notifications/notification_response.dart';
import 'package:application/features/profile/data/models/profile/privacy_model.dart';
import 'package:application/features/profile/data/models/profile/profile_model.dart';
import 'package:application/features/profile/data/models/profile/session_model.dart';
import 'package:application/features/slider/data/models/slider_model.dart';
import 'package:application/features/template/data/models/template_model.dart';

extension HiveRegistrar on HiveInterface {
  void registerAdapters() {
    registerAdapter(AnimeModelAdapter());
    registerAdapter(AvatarModelAdapter());
    registerAdapter(CalendarModelAdapter());
    registerAdapter(ChunkAdapter());
    registerAdapter(DownloadInfosAdapter());
    registerAdapter(DownloadModelAdapter());
    registerAdapter(DownloadStateAdapter());
    registerAdapter(DownloadTaskAdapter());
    registerAdapter(EpisodeModelAdapter());
    registerAdapter(EpisodeNotificationModelAdapter());
    registerAdapter(ExtraInfosAdapter());
    registerAdapter(GenreModelAdapter());
    registerAdapter(ItemModelAdapter());
    registerAdapter(MasterPlaylistAdapter());
    registerAdapter(MediaPlaylistAdapter());
    registerAdapter(NotificationModelAdapter());
    registerAdapter(NotificationResponseAdapter());
    registerAdapter(PaginationAdapter());
    registerAdapter(PrivacyModelAdapter());
    registerAdapter(ProfileModelAdapter());
    registerAdapter(SessionModelAdapter());
    registerAdapter(SessionsModelAdapter());
    registerAdapter(SliderModelAdapter());
    registerAdapter(TemplateModelAdapter());
    registerAdapter(TimelineModelAdapter());
    registerAdapter(TimerModelAdapter());
    registerAdapter(TranslatedModelAdapter());
    registerAdapter(VariantAdapter());
  }
}

extension IsolatedHiveRegistrar on IsolatedHiveInterface {
  void registerAdapters() {
    registerAdapter(AnimeModelAdapter());
    registerAdapter(AvatarModelAdapter());
    registerAdapter(CalendarModelAdapter());
    registerAdapter(ChunkAdapter());
    registerAdapter(DownloadInfosAdapter());
    registerAdapter(DownloadModelAdapter());
    registerAdapter(DownloadStateAdapter());
    registerAdapter(DownloadTaskAdapter());
    registerAdapter(EpisodeModelAdapter());
    registerAdapter(EpisodeNotificationModelAdapter());
    registerAdapter(ExtraInfosAdapter());
    registerAdapter(GenreModelAdapter());
    registerAdapter(ItemModelAdapter());
    registerAdapter(MasterPlaylistAdapter());
    registerAdapter(MediaPlaylistAdapter());
    registerAdapter(NotificationModelAdapter());
    registerAdapter(NotificationResponseAdapter());
    registerAdapter(PaginationAdapter());
    registerAdapter(PrivacyModelAdapter());
    registerAdapter(ProfileModelAdapter());
    registerAdapter(SessionModelAdapter());
    registerAdapter(SessionsModelAdapter());
    registerAdapter(SliderModelAdapter());
    registerAdapter(TemplateModelAdapter());
    registerAdapter(TimelineModelAdapter());
    registerAdapter(TimerModelAdapter());
    registerAdapter(TranslatedModelAdapter());
    registerAdapter(VariantAdapter());
  }
}
